# Generated by Django 4.2.4 on 2023-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MVRS_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MVRS_cat_name', models.CharField(max_length=100)),
                ('MVRS_cat_description', models.TextField()),
            ],
        ),
    ]
