# Generated by Django 4.2.4 on 2023-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('select_vehicle', models.CharField(max_length=255)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MVRS_Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MVRS_cat_name', models.CharField(max_length=100)),
                ('MVRS_cat_description', models.TextField()),
            ],
        ),
    ]
