# Generated by Django 4.2.4 on 2024-05-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MVRS_car_name', models.CharField(max_length=255)),
                ('MVRS_car_description', models.CharField(max_length=255)),
                ('MVRS_car_image', models.ImageField(upload_to='MVRS_Cars')),
                ('car_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.mvrs_category')),
            ],
        ),
        migrations.DeleteModel(
            name='MVRS_Cars',
        ),
    ]
